<?php require_once "views/partials/header.php"; ?>

<div class="dashboard">

<div class="topbar">
<div>
<h1>Rental Finance</h1>
<p>Revenue generated by vehicles managed by you.</p>
</div>
<a class="btn-secondary" href="index.php?page=manager&action=dashboard">Back</a>
</div>

<div class="box">
<div class="table-container">
<table>
<thead>
<tr>
<th>Booking</th>
<th>Customer</th>
<th>Vehicle</th>
<th>Rental Days</th>
<th>Amount</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<?php
$total=0;
while($row=mysqli_fetch_assoc($bookings)):
    if(in_array($row['status'],['approved','picked_up','returned'],true))
        $total += $row['total_amount'];
?>
<tr>
<td><?= e($row['booking_code']); ?></td>
<td><?= e($row['customer_name']); ?></td>
<td><?= e($row['brand']." ".$row['model']); ?></td>
<td><?= e($row['rental_days']); ?></td>
<td><?= CURRENCY." ".e($row['total_amount']); ?></td>
<td><?= e($row['status']); ?></td>
</tr>
<?php endwhile; ?>
</tbody>
</table>
</div>

<h3 style="margin-top:20px;">
Total Rental Revenue: <?= CURRENCY." ".number_format($total,2); ?>
</h3>

</div>
</div>

<?php require_once "views/partials/footer.php"; ?>
